# Generated by Django 4.2.16 on 2024-12-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('main_proffesion', models.CharField(max_length=100)),
                ('shortdescription', models.TextField(max_length=200)),
                ('birthdate', models.DateField()),
                ('website', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('city', models.CharField(max_length=50)),
                ('Age', models.CharField(max_length=50)),
                ('Degree', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Freelance', models.CharField(max_length=50)),
            ],
        ),
    ]
