# Generated by Django 4.2.16 on 2024-12-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birthdate',
            field=models.CharField(max_length=50),
        ),
    ]
